apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: humhub-pv-claim
  namespace: humhub
  labels:
    app: humhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
