apiVersion: v1
kind: Secret
metadata:
  name: humhub-mysql-secret # Nombre que el Deployment de MySQL y HumHub usarán
type: Opaque # Tipo estándar para almacenar datos de usuario (clave-valor)
data:
  # Contraseña del usuario ROOT
  MYSQL_ROOT_PASSWORD: cm9vdGNvbnRyYXNlbmE= #rootcontrasena
  
  # Nombre de la Base de Datos que creará MySQL
  MYSQL_DATABASE: YmFzZWRhdG9zY29udHJhc2VuYQ== #basedatoscontrasena
  
  #  Usuario de la Aplicación HumHub
  MYSQL_USER: dXN1YXJpbw== #usuario
  
  # Contraseña del Usuario de la Aplicación
  MYSQL_PASSWORD: YXBwY29udHJhc2VuYQ== #usuariocontrasena