apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: humhub-monitor
  namespace: default
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: humhub
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
