apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: humhub-monitor
  namespace: default
  labels:
    release: monitoring-stack  # IMPORTANTE: Coincide con el nombre de la relea>
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: humhub # IMPORTANTE: Confirmar que E2 usa esta la>
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
