apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: humhub-monitor
  labels:
    release: kube-prometheus-stack  # Esta etiqueta permite que la instancia principal de Prometheus reconozca la configuración y la integre automáticamente
spec:
  selector:
    matchLabels:
      app: humhub  # Esta etiqueta coincide con el servicio desplegado de HumHub
  endpoints:
  - port: http  # Nombre del puerto definido en el servicio de HumHub
    path: /metrics  # URL interna donde la app mostrará los datos
    interval: 15s  # Frecuencia de lectura
  namespaceSelector:
    matchNames:
    - humhub  # Limitamos la búsqueda del servicio al namespace humhub
