apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: humhub-monitor
  # Esta etiqueta debe coincidir con la release de prometheus (normalmente 'kube-prometheus-stack')
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      # IMPORTANTE: Estas etiquetas deben coincidir con las que el Equipo 2 ponga en el servicio de HumHub
      app: humhub
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - humhub 
    # (O el namespace donde instalen HumHub, normalmente 'default' en proyectos básicos)
