apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: humhub-gitops  # la tarea la llamamos así
  namespace: argocd    
spec:
  project: default
  
  #En source le pasamos el lugar donde se encuentran los archivos 
  source:
    repoURL: https://github.com/AntonioBelloCastro/humhub-gitops-gr7.git
    targetRevision: modificaciones  # que coja los cambios del main
    path: base            # va a leer la carpeta base (que es donde tenemos toda la estructura)
    directory:
      recurse: true #para que mire los subdirectorios
  
  #Aquí es donde tengo que desplegar todo
  destination:
    server: https://kubernetes.default.svc  #apunta al cluster de kubernetes interno que tenemos montado
    namespace: humhub     # En el namespace que creamos

  #aquí se le dice que tiene que hacer, cómo tiene que actuar
  syncPolicy:
    automated:
      prune: true       # si se borra algo en git, que lo borre tb argocd
      selfHeal: true    # las correcciones que se hagan a mano que las restablezca a lo que dice el git
    syncOptions:
      - CreateNamespace=true # Si no existe el namespace humhub, lo creas