apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AntonioBelloCastro/humhub-gitops-gr7.git' # ¡CAMBIA ESTO POR TU URL REAL!
    targetRevision: HEAD
    path: monitoring # Apunta a tu carpeta preparada en el Paso 1
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring # Se desplegará en un namespace separado para orden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Creará el namespace 'monitoring' si no existe
